springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/openapi3.json
    path: /docs/swagger

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 464751386701-7uf06bo8i60u2sm4r0t73am0sdgi9k8e.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: '{baseUrl}/oauth/callback/google'
            scope: profile, email

          naver:
            client-id: tmNT3edNBsSeEAtYTlB4
            client-secret: iQ9CdhzUwP
            redirect-uri: '{baseUrl}/oauth/callback/naver'
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: 68d9607335ba087fd85b8145a527c524
            client-secret: gpSQEOyAnA5vrMAC9HGyggcn7wFmDeBD
            redirect-uri: '{baseUrl}/oauth/callback/kakao'
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  session:
    store-type: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meetnow?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwer1234!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    secretKey: Q1UxGPyO7FXitc1VJTFJ779rKhhxQqIs3u8HEtgX735IcQBcJAxYXm9ISgA6UdBTBGZsi0yB6nchGA+iks1tbg==
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: WkdGN2tMZE9qM3RyTDRqYVhPZG5uV2t5QlJGV3VwREl1TFdGbFJXVlR3WkhwdldhQ1JX
  access:
    expiration: 30000000
  refresh:
    expiration: 30000000
