name: CD-Stable

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-stable:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: SSH to Stable EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STABLE_EC2_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/meetnow

            echo "▶️ Redis 컨테이너 확인 및 실행"
            if ! docker ps --format '{{.Names}}' | grep -q "meetnow-redis"; then
              docker run -d --name meetnow-redis -p 6379:6379 redis:latest
              echo "✅ Redis 컨테이너 실행 완료"
            else
              echo "ℹ️ Redis 컨테이너 이미 실행 중"
            fi

            echo "▶️ Stable 컨테이너 실행"
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull haerizian561024/meetnow-server:stable

            if docker ps -a --format '{{.Names}}' | grep -q "meetnow-server-stable"; then
              echo "🗑 기존 Stable 컨테이너 삭제"
              docker rm -f meetnow-server-stable
            fi

            docker run -d --name meetnow-server-stable \
              --env-file .env.prod \
              -p 8083:8080 \
              haerizian561024/meetnow-server:stable java -XX:+IgnoreUnrecognizedVMOptions -XX:-UseContainerSupport -jar app.jar

            echo "✅ Stable 컨테이너 배포 완료"
